# Generated by Django 3.0.7 on 2021-09-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarksection', '0003_auto_20210902_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='image_field',
            field=models.URLField(default='none', max_length=1000, null=True),
        ),
    ]
