# Generated by Django 3.0.7 on 2021-12-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarksection', '0004_auto_20210902_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='tags',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='tags',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.DeleteModel(
            name='DiscoverBookmark',
        ),
    ]
