# Generated by Django 3.0.7 on 2021-12-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarksection', '0006_bookmark_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
