# Generated by Django 3.0.7 on 2021-12-07 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0004_timeline_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='tags',
        ),
    ]
